spring:
  datasource:
    url: jdbc:postgresql://<PROD_DB_HOST>:5432/loreatlas
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

  jpa:
    show-sql: false
    hibernate:
      ddl-auto: validate

server:
  port: 8080

logging:
  level:
    root: INFO
    org.hibernate.SQL: WARN