spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/loreatlas_dev
    username: dev
    password: dev

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update

logging:
  level:
    root: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE